name: ps5_games
description: "A new Flutter project."
publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  build_runner: ^2.4.7
  cached_network_image: ^3.3.0
  dio: ^5.4.0
  either_dart: ^1.0.0
  envied: ^0.5.2
  envied_generator: ^0.5.2
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  flutter_widget_from_html: ^0.14.8
  get: ^4.6.6
  intl: ^0.18.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  retrofit: ^4.0.3
  retrofit_generator: ^8.0.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
